[package]
name = "tree-sitter-qd"
description = "Quarkdown grammar for tree-sitter"
version = "0.5.1"
authors = ["Kinten Le"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "quarkdown"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/kinten108101/tree-sitter-quarkdown"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "tree-sitter-quarkdown/src/*",
  "tree-sitter-quarkdown-inline/src/*",
  "tree-sitter-quarkdown/grammar.js",
  "tree-sitter-quarkdown-inline/grammar.js",
  "tree-sitter-quarkdown/queries/*",
  "tree-sitter-quarkdown-inline/queries/*",
  "common/grammar.js",
  "common/html_entities.json",
]

[features]
parser = ["tree-sitter"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"
tree-sitter = { version = "0.24", optional = true }

[dev-dependencies]
tree-sitter = "0.24.3"

[build-dependencies]
cc = "1.1.22"

[[bin]]
name = "benchmark"
path = "bindings/rust/benchmark.rs"
required-features = ["parser"]

[profile.release]
debug = true

[package.metadata.docs.rs]
features = ["parser"]
rustdoc-args = ["--cfg", "docsrs"]
